# Generated by Django 5.2.3 on 2026-01-26 13:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DniKursowe',
            fields=[
                ('dnia_lp', models.AutoField(primary_key=True, serialize=False)),
                ('data_dnia', models.DateField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'Dni_kursowe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instruktorostwo',
            fields=[
                ('instruktoro_lp', models.AutoField(primary_key=True, serialize=False)),
                ('instruktoro_name', models.CharField(blank=True, null=True)),
                ('instruktoro_surname', models.CharField(blank=True, null=True)),
                ('instruktoro_phone', models.IntegerField()),
                ('instruktoro_email', models.CharField()),
                ('instruktoro_degree', models.CharField()),
            ],
            options={
                'db_table': 'Instruktorostwo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Klientela',
            fields=[
                ('uczestniko_lp', models.AutoField(primary_key=True, serialize=False)),
                ('uczestniko_name', models.CharField(blank=True, null=True)),
                ('uczestniko_surname', models.CharField(blank=True, null=True)),
                ('uczestniko_phone', models.IntegerField()),
                ('uczestniko_email', models.CharField()),
            ],
            options={
                'db_table': 'Klientela',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KursyWszystkie',
            fields=[
                ('kursu_lp', models.AutoField(primary_key=True, serialize=False)),
                ('kursu_kod', models.CharField(blank=True, null=True, unique=True)),
                ('kursu_schedule', models.CharField(blank=True, null=True)),
                ('kursu_data_start', models.DateField(blank=True, null=True)),
                ('kursu_data_end', models.DateField(blank=True, null=True)),
                ('kursu_data_wyd', models.DateField(blank=True, null=True)),
                ('kursu_prise', models.IntegerField(blank=True, null=True)),
                ('kursu_name', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Kursy_wszystkie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrzypisanieDoDniaKursu',
            fields=[
                ('przypisanie_instr_lp', models.AutoField(db_column='przypisanie_Instr_lp', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'przypisanie_do_dnia_Kursu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrzypisOpiekU18',
            fields=[
                ('przypisuou18_lp', models.AutoField(db_column='przypisuOU18_lp', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'przypis_Opiek_U18',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UczestUnder18',
            fields=[
                ('uczestu18_lp', models.AutoField(db_column='uczestU18_lp', primary_key=True, serialize=False)),
                ('uczestu18_name', models.CharField(blank=True, db_column='uczestU18_name', null=True)),
                ('uczestu18_surname', models.CharField(blank=True, db_column='uczestU18_surname', null=True)),
                ('uczestu18_phone', models.IntegerField(blank=True, db_column='uczestU18_phone', null=True)),
                ('uczestu18_email', models.CharField(blank=True, db_column='uczestU18_email', null=True)),
            ],
            options={
                'db_table': 'Uczest_under18',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZapisyNaKursy',
            fields=[
                ('zapisu_lp', models.AutoField(primary_key=True, serialize=False)),
                ('data_zapisu_nakrs', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zapisy_na_Kursy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=250)),
                ('file_upload', models.FileField(upload_to='basepage/static')),
                ('upload_date', models.DateField(default=datetime.datetime(2026, 1, 26, 14, 30, 32, 520183))),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user_A', models.CharField(max_length=250)),
                ('code_user_A', models.PositiveIntegerField(null=True)),
                ('total_user_A', models.PositiveIntegerField(null=True)),
                ('sd_user_A', models.PositiveIntegerField(null=True)),
                ('name_user_B', models.CharField(max_length=250)),
                ('code_user_B', models.PositiveIntegerField(null=True)),
                ('total_user_B', models.PositiveIntegerField(null=True)),
                ('sd_user_B', models.PositiveIntegerField(null=True)),
                ('file_uploaded', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basepage.file')),
            ],
        ),
    ]
