# Generated by Django 6.0.2 on 2026-03-03 16:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DzienKursu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dnia', models.DateField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Dzień_kursu',
                'verbose_name_plural': 'Dni_kursowe',
            },
        ),
        migrations.CreateModel(
            name='Instruktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100, verbose_name='Imię')),
                ('imie_dopelniacz', models.CharField(blank=True, max_length=100, null=True)),
                ('nazwisko', models.CharField(max_length=150, verbose_name='Nazwisko')),
                ('nazwisko_dopelniacz', models.CharField(blank=True, max_length=150, null=True)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('stopien', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Instruktoro',
                'verbose_name_plural': 'Instruktory',
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=150, verbose_name='Nazwisko')),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klientela',
            },
        ),
        migrations.CreateModel(
            name='OceniajStrone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wyslania', models.DateTimeField(auto_now_add=True)),
                ('fajnosc', models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('-2', 'ale słaba!'), ('-1', 'ma istotne wady'), ('0', 'jest w porządku'), ('1', 'fajna'), ('2', 'kurde, ósmy cud świata!')], max_length=50, verbose_name='Czy strona jest przyjemna w odbiorze?')),
                ('czytelnosc', models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('-2', 'nie mam pojęcia, jak poruszać się po stronie'), ('-1', 'w pewnych miejsca nie wiadomo gdzie kliknąć'), ('1', 'można zrozumieć, co robić na stronie'), ('2', 'bardzo łatwo wszystko znaleźć')], max_length=50, verbose_name='Czy łatwo jest poruszać się po stronie?')),
                ('co_zmienic', models.TextField(blank=True, max_length=5000, verbose_name='Napisz tutaj o ewentualnych błędach, jeśli są na stronie')),
                ('co_dodac', models.TextField(blank=True, max_length=5000, verbose_name='Wpisz tutaj, czego Twoim zdaniem brakuje na stronie')),
                ('sugestie', models.TextField(blank=True, max_length=5000, verbose_name='inne uwagi')),
            ],
            options={
                'verbose_name': 'Wynik oceny',
                'verbose_name_plural': 'Wyniki ocen strony',
                'ordering': ['-data_wyslania'],
            },
        ),
        migrations.CreateModel(
            name='PlikImportu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_pliku', models.CharField(max_length=250)),
                ('plik', models.FileField(upload_to='imports/%Y/%m/%d/')),
                ('data_wgrania', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plik importu',
                'verbose_name_plural': 'Pliki importu',
            },
        ),
        migrations.CreateModel(
            name='UczestUnder18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=150, verbose_name='Nazwisko')),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Niepełnoletnie',
                'verbose_name_plural': 'Niepełnoletni',
            },
        ),
        migrations.CreateModel(
            name='Wydarzenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=15, unique=True)),
                ('schedule', models.CharField(max_length=50)),
                ('data_start', models.DateField()),
                ('data_end', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01, message='Cena musi być większa od zera'), django.core.validators.MaxValueValidator(9000, message='Cena nie może przekraczać 50 000 zł')], verbose_name='Cena')),
                ('price_promo', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01, message='Cena musi być większa od zera'), django.core.validators.MaxValueValidator(9000, message='Cena nie może przekraczać 50 000 zł')], verbose_name='promo Cena')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
            },
        ),
        migrations.CreateModel(
            name='DaneKursuZPliku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_kursu', models.CharField(max_length=250)),
                ('kod_kursu', models.CharField(blank=True, max_length=50, null=True)),
                ('liczba_uczestnikow', models.PositiveIntegerField(default=0)),
                ('cena_bazowa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('importowany_plik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dane', to='basepage.plikimportu')),
            ],
            options={
                'verbose_name': 'Dane z pliku',
                'verbose_name_plural': 'Dane z plików',
            },
        ),
        migrations.CreateModel(
            name='PrzypisOpiekU18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opiekuno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_podopieczne', to='basepage.klient')),
                ('podopieczne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='do_opiekuno', to='basepage.uczestunder18')),
            ],
            options={
                'verbose_name': 'Przypisanie podopieczniko do opiekuno',
                'verbose_name_plural': 'Przypisania podopiecznikostwa do opiekunostwa',
            },
        ),
        migrations.CreateModel(
            name='PrzypisanieDoDniaKursu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzien_kursowy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='przypisania', to='basepage.dzienkursu')),
                ('instruktoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wydarzenia', to='basepage.instruktor')),
                ('wydarzenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruktorostwo', to='basepage.wydarzenie')),
            ],
            options={
                'verbose_name': 'Przypisanie instruktora do dnia Kursu',
                'verbose_name_plural': 'Przypisania instruktorostwa do dni Kursu',
            },
        ),
        migrations.CreateModel(
            name='WynikAnkiety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wyslania', models.DateTimeField(auto_now_add=True)),
                ('plec', models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('0', 'nie odpowiem na to pytanie'), ('K', 'kobieta'), ('M', 'mężczyzna'), ('inna', 'inna opcja')], max_length=50, verbose_name='Czy możesz określić swoją płeć?')),
                ('wiek', models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('nie', 'nie powiem'), ('nastolatek', '14-18 lat'), ('mlody_dorosly', '18-30 lat'), ('sredni_wiek', '30-50 lat'), ('pozna_doroslosc', 'niemalże dojrzałym')], max_length=50, verbose_name='W jakim jesteś przedziale wiekowym?')),
                ('czy_polecisz', models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('tak', 'Tak'), ('tak_ale', 'tak, ale...'), ('neutralnie', 'ani tak, ani nie'), ('odradzam', 'odradzałobym'), ('zniechecam', 'bardzo zniechęcało')], max_length=50, verbose_name='Czy polecisz nas znajomej osobie?')),
                ('startowa_wiedza', models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('1', 'Total tabula rasa'), ('2', 'parę razy obserwowałom, jak inni obsługują jacht'), ('3', 'Raz czy dwa razy coś tam porobiłom na jachcie'), ('4', 'Trochę się żeglowało'), ('5', 'Niemałe doświadczenie, również za sterem')], max_length=50, verbose_name='Jaki był poziom Twoich umiejętności przed kursem?')),
                ('nabycie_wiedzy', models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('super', 'Super'), ('moze_byc', 'Może być'), ('slabo', 'Słabo')], max_length=50, verbose_name='Jak oceniasz przyrost swoich umiejętności w zakresie prowadzenia jachtu?')),
                ('prowadzenie_rejsu', models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('super', 'Tak, spoko to ogarnę'), ('moze_byc', 'Popłynę, ale z duszą na ramieniu'), ('slabo', 'Niespecjalnie')], max_length=50, verbose_name='Czy czujesz się osobą gotową do samodzielnego poprowadzenia rejsu?')),
                ('uwagi', models.TextField(blank=True, max_length=5000, verbose_name='Dodatkowe uwagi')),
                ('wybrani_instruktorzy', models.ManyToManyField(to='basepage.instruktor', verbose_name='Kto prowadził Twoje zajęcia na jachcie?')),
            ],
            options={
                'verbose_name': 'Wynik ankiety',
                'verbose_name_plural': 'Wyniki ankiet',
                'ordering': ['-data_wyslania'],
            },
        ),
        migrations.CreateModel(
            name='OcenaSzczegolowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena_punktualnosc', models.IntegerField()),
                ('ocena_wiedza', models.IntegerField()),
                ('ocena_nauczanie', models.IntegerField()),
                ('ocena_zachowanie', models.IntegerField()),
                ('instruktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basepage.instruktor')),
                ('ankieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny', to='basepage.wynikankiety')),
            ],
        ),
        migrations.CreateModel(
            name='ZapisNaKurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zapisu_nakrs', models.DateTimeField(auto_now_add=True)),
                ('instruktoro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zapisania_instruktoro', to='basepage.instruktor')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapisania_kursowe', to='basepage.wydarzenie')),
                ('uczestniko', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zapisania_uczestniko', to='basepage.klient')),
                ('uczestniko_U18', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zapisania_nieletne', to='basepage.uczestunder18')),
            ],
            options={
                'verbose_name': 'Zapisanie na Wydarzenie',
                'verbose_name_plural': 'Zapisania na Wydarzenia',
            },
        ),
    ]
