# Generated by Django 6.0.2 on 2026-03-03 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wydarzenie',
            name='price_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Cena musi być większa od zera'), django.core.validators.MaxValueValidator(9000, message='Cena nie może przekraczać 50 000 zł')], verbose_name='promo Cena'),
        ),
    ]
