# Generated by Django 6.0.2 on 2026-03-04 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0002_alter_wydarzenie_price_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocenaszczegolowa',
            name='ocena_nauczanie',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='ocenaszczegolowa',
            name='ocena_punktualnosc',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='ocenaszczegolowa',
            name='ocena_wiedza',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='ocenaszczegolowa',
            name='ocena_zachowanie',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='oceniajstrone',
            name='czytelnosc',
            field=models.SmallIntegerField(choices=[('', 'Wybierz odpowiedź...'), (-2, 'nie mam pojęcia, jak poruszać się po stronie'), (-1, 'w pewnych miejsca nie wiadomo gdzie kliknąć'), (1, 'można zrozumieć, co robić na stronie'), (2, 'bardzo łatwo wszystko znaleźć')], validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)], verbose_name='Czy łatwo jest poruszać się po stronie?'),
        ),
        migrations.AlterField(
            model_name='oceniajstrone',
            name='fajnosc',
            field=models.SmallIntegerField(choices=[('', 'Wybierz odpowiedź...'), (-2, 'ale słaba!'), (-1, 'ma istotne wady'), (0, 'jest w porządku'), (1, 'fajna'), (2, 'kurde, ósmy cud świata!')], validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)], verbose_name='Czy strona jest przyjemna w odbiorze?'),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01, message='Cena musi być większa od zera'), django.core.validators.MaxValueValidator(9000, message='Cena nie może przekraczać 9 000 zł')], verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='price_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Cena musi być większa od zera'), django.core.validators.MaxValueValidator(9000, message='Cena nie może przekraczać 9 000 zł')], verbose_name='promo Cena'),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='czy_polecisz',
            field=models.SmallIntegerField(choices=[('', 'Wybierz odpowiedź...'), (-2, 'będę zniechęcało. Bardzo'), (-1, 'odradzałobym'), (0, 'ani tak, ani nie'), (1, 'tak, ale...'), (2, 'Tak')], validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)], verbose_name='Czy polecisz nas znajomej osobie?'),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='nabycie_wiedzy',
            field=models.SmallIntegerField(choices=[('', 'Wybierz odpowiedź...'), (1, 'Słabo'), (2, 'Może być'), (3, 'Super')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Jak oceniasz przyrost swoich umiejętności?'),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='plec',
            field=models.SmallIntegerField(choices=[('', 'Wybierz odpowiedź...'), (0, 'nie odpowiem na to pytanie'), (1, 'kobieta'), (2, 'mężczyzna'), (3, 'inna opcja')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Czy możesz określić swoją płeć?'),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='prowadzenie_rejsu',
            field=models.SmallIntegerField(choices=[('', 'Wybierz odpowiedź...'), (1, 'Niespecjalnie'), (2, 'Popłynę, ale z duszą na ramieniu'), (3, 'Tak, spoko to ogarnę')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Czy czujesz się osobą gotową do samodzielnego poprowadzenia rejsu?'),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='startowa_wiedza',
            field=models.SmallIntegerField(choices=[('', 'Wybierz odpowiedź...'), (1, 'Total tabula rasa'), (2, 'parę razy obserwowałom, jak inni obsługują jacht'), (3, 'Raz czy dwa razy coś tam porobiłom na jachcie'), (4, 'Trochę się żeglowało'), (5, 'Niemałe doświadczenie, również za sterem')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Jaki był poziom Twoich umiejętności przed kursem?'),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='wiek',
            field=models.SmallIntegerField(choices=[('', 'Wybierz odpowiedź...'), (0, 'nie powiem'), (1, '14-18 lat'), (2, '18-30 lat'), (3, '30-50 lat'), (4, 'niemalże dojrzałym')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='W jakim jesteś przedziale wiekowym?'),
        ),
    ]
