# Generated by Django 6.0.2 on 2026-02-21 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0003_alter_file_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 21, 1, 40, 56, 711279)),
        ),
    ]
