# Generated by Django 6.0.2 on 2026-03-04 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0003_alter_ocenaszczegolowa_ocena_nauczanie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocenaszczegolowa',
            options={'verbose_name': 'Ocena instruktoro', 'verbose_name_plural': 'Oceny instruktorostwa'},
        ),
        migrations.AlterField(
            model_name='ocenaszczegolowa',
            name='ocena_zachowanie',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
