# Generated by Django 6.0.2 on 2026-02-21 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0004_alter_file_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 21, 1, 56, 1, 363681)),
        ),
        migrations.CreateModel(
            name='WynikAnkiety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wyslania', models.DateTimeField(auto_now_add=True)),
                ('plec', models.CharField(choices=[('0', 'nie odpowiem na to pytanie'), ('K', 'kobieta'), ('M', 'mężczyzna'), ('inna', 'inna opcja')], default='tak', max_length=50)),
                ('wiek', models.CharField(choices=[('nie', 'nie powiem'), ('nastolatek', '14-18 lat'), ('mlody_dorosly', '18-30 lat'), ('sredni_wiek', '30-50 lat'), ('pozna_doroslosc', 'niemalże dojrzałym')], default='tak', max_length=50)),
                ('czy_polecisz', models.CharField(choices=[('tak', 'Tak'), ('tak_ale', 'tak, ale...'), ('neutralnie', 'ani tak, ani nie'), ('odradzam', 'odradzałobym'), ('zniechecam', 'bardzo zniechęcało')], default='tak', max_length=50)),
                ('startowa_wiedza', models.CharField(choices=[('0', 'Total tabula rasa'), ('1', 'parę razy obserwowałom, jak inni obsługują jacht'), ('2', 'Raz czy dwa razy coś tam porobiłom na jachcie'), ('3', 'Trochę się żeglowało'), ('4', 'Niemałe doświadczenie, również za sterem')], default='tak', max_length=50)),
                ('nabycie_wiedzy', models.CharField(choices=[('super', 'Super'), ('moze_byc', 'Może być'), ('slabo', 'Słabo')], default='tak', max_length=50)),
                ('prowadzenie_rejsu', models.CharField(choices=[('super', 'Tak, spoko to ogarnę'), ('moze_byc', 'Popłynę, ale z duszą na ramieniu'), ('slabo', 'Niespecjalnie')], default='tak', max_length=50)),
                ('uwagi', models.TextField(blank=True, max_length=5000)),
                ('wybrani_instruktorzy', models.ManyToManyField(to='basepage.instruktorostwo')),
            ],
            options={
                'verbose_name': 'Wynik ankiety',
                'verbose_name_plural': 'Wyniki ankiet',
                'ordering': ['-data_wyslania'],
            },
        ),
    ]
