# Generated by Django 6.0.2 on 2026-02-21 02:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0005_alter_file_upload_date_wynikankiety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 21, 3, 37, 59, 837130)),
        ),
        migrations.CreateModel(
            name='OcenaSzczegolowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena_punktualnosc', models.IntegerField()),
                ('ocena_wiedza', models.IntegerField()),
                ('ocena_nauczanie', models.IntegerField()),
                ('ocena_zachowanie', models.IntegerField()),
                ('ankieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny', to='basepage.wynikankiety')),
                ('instruktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basepage.instruktorostwo')),
            ],
        ),
    ]
