# Generated by Django 6.0.2 on 2026-02-21 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0006_alter_file_upload_date_ocenaszczegolowa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 21, 4, 0, 55, 586900)),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='startowa_wiedza',
            field=models.CharField(choices=[('1', 'Total tabula rasa'), ('2', 'parę razy obserwowałom, jak inni obsługują jacht'), ('3', 'Raz czy dwa razy coś tam porobiłom na jachcie'), ('4', 'Trochę się żeglowało'), ('5', 'Niemałe doświadczenie, również za sterem')], default='tak', max_length=50),
        ),
    ]
