# Generated by Django 6.0.2 on 2026-02-21 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0007_alter_file_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 21, 4, 24, 56, 632874)),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='czy_polecisz',
            field=models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('tak', 'Tak'), ('tak_ale', 'tak, ale...'), ('neutralnie', 'ani tak, ani nie'), ('odradzam', 'odradzałobym'), ('zniechecam', 'bardzo zniechęcało')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='nabycie_wiedzy',
            field=models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('super', 'Super'), ('moze_byc', 'Może być'), ('slabo', 'Słabo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='plec',
            field=models.CharField(blank=True, choices=[('', 'Wybierz odpowiedź...'), ('0', 'nie odpowiem na to pytanie'), ('K', 'kobieta'), ('M', 'mężczyzna'), ('inna', 'inna opcja')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='prowadzenie_rejsu',
            field=models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('super', 'Tak, spoko to ogarnę'), ('moze_byc', 'Popłynę, ale z duszą na ramieniu'), ('slabo', 'Niespecjalnie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='startowa_wiedza',
            field=models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('1', 'Total tabula rasa'), ('2', 'parę razy obserwowałom, jak inni obsługują jacht'), ('3', 'Raz czy dwa razy coś tam porobiłom na jachcie'), ('4', 'Trochę się żeglowało'), ('5', 'Niemałe doświadczenie, również za sterem')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='wiek',
            field=models.CharField(blank=True, choices=[('', 'Wybierz odpowiedź...'), ('nie', 'nie powiem'), ('nastolatek', '14-18 lat'), ('mlody_dorosly', '18-30 lat'), ('sredni_wiek', '30-50 lat'), ('pozna_doroslosc', 'niemalże dojrzałym')], max_length=50),
        ),
    ]
