# Generated by Django 6.0.2 on 2026-02-23 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0009_alter_file_upload_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OceniajStrone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wyslania', models.DateTimeField(auto_now_add=True)),
                ('fajnosc', models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('-2', 'ale słaba!'), ('-1', 'ma istotne wady'), ('0', 'jest w porządku'), ('1', 'fajna'), ('2', 'kurde, ósmy cud świata!')], max_length=50, verbose_name='Czy strona jest przyjemna w odbiorze?')),
                ('czytelnosc', models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('-2', 'nie mam pojęcia, jak poruszać się po stronie'), ('-1', 'w pewnych miejsca nie wiadomo gdzie kliknąć'), ('1', 'jest zrozumiałe, co robić na stronie'), ('2', 'bardzo łatwo wszystko znaleźć')], max_length=50, verbose_name='Czy łatwo jest poruszać się po stronie?')),
                ('co_zmienic', models.TextField(blank=True, max_length=5000, verbose_name='Napisz tutaj o ewentualnych błędach, jeśli są na stronie')),
                ('co_dodac', models.TextField(blank=True, max_length=5000, verbose_name='Wpisz tutaj, czego Twoim zdaniem brakuje na stronie')),
                ('sugestie', models.TextField(blank=True, max_length=5000, verbose_name='inne uwagi')),
            ],
            options={
                'verbose_name': 'Wynik oceny',
                'verbose_name_plural': 'Wyniki ocen',
                'ordering': ['-data_wyslania'],
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 23, 14, 0, 39, 129406)),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='plec',
            field=models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('0', 'nie odpowiem na to pytanie'), ('K', 'kobieta'), ('M', 'mężczyzna'), ('inna', 'inna opcja')], max_length=50, verbose_name='Czy możesz określić swoją płeć?'),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='wiek',
            field=models.CharField(choices=[('', 'Wybierz odpowiedź...'), ('nie', 'nie powiem'), ('nastolatek', '14-18 lat'), ('mlody_dorosly', '18-30 lat'), ('sredni_wiek', '30-50 lat'), ('pozna_doroslosc', 'niemalże dojrzałym')], max_length=50, verbose_name='W jakim jesteś przedziale wiekowym?'),
        ),
        migrations.AlterField(
            model_name='wynikankiety',
            name='wybrani_instruktorzy',
            field=models.ManyToManyField(to='basepage.instruktorostwo', verbose_name='Kto prowadził Twoje zajęcia na jachcie?'),
        ),
    ]
